### ISSUE TITLE
requirements are not clear

### ISSUE THREAD

**Issue by alexandermitop** [junxzm1990/afl-pt#4]
Hello

1. "we only tested Ptrix on bare metal machine running Ubuntu 14.04." Trusty (last kernel 3.x)
INSTALL.md note 14.04.5 Trusty however install.sh checks for a 4.4.0* kernel (Xenial). 

2. Is it possible to run several afl instances for parallel jobs?

**Comment by mudongliang** [comment]
1. We have modified our document a little according to your question;
2. Yes, it supports.
